### PR TITLE
pynsource project with goldstar611 snapcraft.yaml

### PR DESCRIPTION
**Pull request by abulka**
My entire pynsource (Python UML diagramming tool, wxpython) project incl. snapcraft.yaml based on  goldstar611 snapcraft.yaml

```
python3 setup.py sdist
pip install -e .
pynsource
```
works and builds and runs.

```
snapcraft --use-lxd
```
fails as discussed at https://github.com/goldstar611/chirp/issues/7

### CODE REVIEW

**Comment by goldstar611** [comment]
Let's see what Canonical build serves do. https://launchpad.net/~build.snapcraft.io/+snap/464a28057b661fc4b39cffcf8ffa2702/+build/2049265

**Comment by abulka** [comment]
Not sure how the last build end up - the link you sent to the Canonical build servers log was for an earlier run with some bad paths that you later fixed. 

I will try the latest version of snapcraft which was just released, as per your comment.

**Comment by goldstar611** [comment]
Hey, it built and released but it took 3 hours which I think was mostly building wxpython
image

https://launchpad.net/~build.snapcraft.io/+snap/464a28057b661fc4b39cffcf8ffa2702/+build/2049528

**Comment by goldstar611** [comment]
:)
image

**Comment by abulka** [comment]
Wow cool. I wonder if it will release to the snapstore (which was my problem re symlinks) - can't push your snap because the name is already taken, so am building myself on launchpad and waiting... You are right, insane 3 hour process. Though to be fair, I have found that unless you specify a wxpython wheel e.g. `-f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04
wxPython` in the requirements then specifying just `wxpython` seems to trigger a full build from source on linux. 

As for the latest snapcraft `snapcraft 7.3.1.post17+git8b3ed19b` - can't seem to try it yet despite the claim that it is stable. `snap refresh snapcraft` only gets me to 7.3.1 and github actions `uses: snapcore/action-build@v1` also uses 7.3.1 not the very latest. Not sure what canonical servers will use as I am still waiting for the build log...

**Comment by abulka** [comment]
I managed to build this project locally using snapcraft `7.3.1.post20+git13719604` - and it even pushed to the snapstore, which was my main problem. Next step is to remove your workarounds and try it again...

**Comment by abulka** [comment]
I removed your workarounds and whilst the snap built and ran, pushing it to the snap store failed with the usual symbolic link errors. 
```
snapcraft upload *.snap --release edge
Issues while processing snap:g                                                                               
- package contains external symlinks: bin/python -> python3, bin/python3 -> /snap/gnome-42-2204-sdk/83/usr/bin/python3.10, bin/python3.10 -> python3
```
I'll report to the main forum topic https://forum.snapcraft.io/t/core22-gnome-extension-and-broken-symlinks/32900/25 

P.S. Thanks so much for your previous help on this.

**Pull request merged**
